[package]
name = "imagine"
license = "MIT"
version = "0.1.0"
authors = ["Connor Brewster <connor.brewster@eagles.oc.edu>"]
edition = "2018"

[dependencies]
gleam = "0.6.8"
glutin = "0.19.0"
webrender = {git="https://github.com/servo/webrender/"}
